baseurl = "https://rodgersgitau.github.io"
languageCode = "en-us"
homepage = "https://rodgersgitau.github.io"
title = "Rodgers M Gitau: Software Engineer"
pluralizeListTitles = true
pygmentsUseClasses = true
pygmentsCodefences = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2

[author]
name = "Rodgers M Gitau"
profile = ""
homepage = "https://github.com/rodgersgitau"

[taxonomies]
tag = "tags"

[params]
intro = true
dateFormat= "Mon, Jan 2, 2006"
readingTime = true
readingTimeText = "Estimated reading time"

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Blog"
url = "/post"
weight = 1
