[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/about/"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
